172.31.27.37
[web]
172.31.27.32
[app]
172.31.27.33
[db]
172.31.27.34
172.31.27.35

[local]
localhost

[local:vars]
Course="DevOps with AWS"
Trainer="Sivakumar"
Duration="3.5months"
#Wishes="Morning from inventory"

[all:children]
web
app
db