172.31.27.37
[web]
172.31.27.32
[app]
172.31.27.33
[db]
172.31.27.34
172.31.27.35
[local]
localhost
[localhost:vars]
Course="DevOps with AWS"
Trainer="Sivakumar"
Duration="3.5months"


[all:children]
web
app
db