- name: Install and run nginx server
  hosts: app
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: service nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

