- name: Declare variables
  hosts: localhost
  vars: #Play level variables
    Course: Terraform
    Trainer: Joindevops
    Duration: 15hrs
  tasks:
  - name: variable declaration
    vars: #Task level variables
    Course: DevOps
    Trainer: Joindevops
    Duration: 150hrs
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}} from {{Trainer}}, Duration is {{Duration}}"

  - name: override information
    ansible.builtin.debug:
       msg: "Hi, I am learning {{Course}} from {{Trainer}}, Duration is {{Duration}}"
